# Copyright (C) 2024 psionicprjkt

name: build-default

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Android Build Environment
        run: |
          git clone https://github.com/akhilnarang/scripts x
          cd x/setup && bash android_build_env.sh

      - name: Setup Repository & Resources
        run: |
          git config --global user.name "KitsuNeko" && git config --global user.email konjikin5@gmail.co.
          git clone --recursive --depth=1 https://github.com/Konjikin/android_kernel_realme_mt6785 mt6785 && cd mt6785
          git clone --depth=1 https://github.com/psionicprjkt/aarch64-linux-android-4.9 arm64 && git clone --depth=1 https://github.com/psionicprjkt/arm-linux-androideabi-4.9 arm32
          wget --quiet https://github.com/XSans0/WeebX-Clang/releases/download/WeebX-Clang-18.1.5-release/WeebX-Clang-18.1.5.tar.gz -O "weebx-clang.tar.gz"
          mkdir clang && tar -xf weebx-clang.tar.gz -C clang && rm -f weebx-clang.tar.gz

      - name: Setup Version
        run: |
          cd mt6785
          v=$(cat version)
          d="arch/arm64/configs/RM6785_defconfig"
          sed -i 's/CONFIG_KSU=y/CONFIG_KSU=n/' $d
          sed -i 's/\(CONFIG_LOCALVERSION="-KitsuNeko-\)kernelsu-\(.*"\)/\1\2/' $d
          sed -i 's/\(CONFIG_LOCALVERSION="-KitsuNeko-\).*"/\1'"$v\"/" $d

      - name: Check Version Kernel
        run: |
          cd mt6785
          kv=$(make kernelversion 2>/dev/null)
          d="arch/arm64/configs/RM6785_defconfig"
          echo "Kernel Version: $kv"
          echo "Local Version: $(grep CONFIG_LOCALVERSION= $d | cut -d '"' -f2)"

      - name: Setup Build Kernel
        run: cd mt6785 && bash build-default.sh

      - name: Setup ENV
        run: |
          echo "RELEASE_DATE=$(date +"%d%m%Y")" >> "$GITHUB_ENV"
          echo "VERSION_KERNEL=$(cat version)" >> "$GITHUB_ENV"

      - name: Setup Release Kernel
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "Default"
          prerelease: false
          title: KitsuNeko-kernel-RM6785-${{ env.RELEASE_DATE }}-${{ env.VERSION_KERNEL }}
          files: |
            mt6785/AnyKernel/psionic-kernel-RM6785*

